version: '2.1'
services:
  config:
    image: config
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  discovery:
    image: discovery
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8762:8762
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    image: gateway
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 4000:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  scenario-service:
    image: scenario-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  program-service:
    image: program-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"




