hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    scenario-service:
        path: /api/scenario/**
        serviceId: scenario-service
        stripPrefix: false
        sensitiveHeaders:

    program-service:
        path: /api/program/**
        serviceId: program-service
        stripPrefix: false
        sensitiveHeaders:

server:
  port: 4000
